### ISSUE TITLE
Request for code release

### ISSUE THREAD

**Issue by yashmaurya01** [yeachan-kr/c2a#2]
Hi,
I'm very interested in the C2A algorithm and would like to try it on some other datasets. I'm trying to experiment with some ideas and it would be really helpful if you could release the code for the "Client-Customized Adaptation for Parameter-Efficient Federated Learning" paper as mentioned in the footnotes about the code availability on GitHub.

Thanks,
Yash

**Comment by yeachan-kr** [comment]
Hi! 

Thanks for having interest in our work and sorry for the delayed release.

We now have uploaded the implementations of c2a. 

Thanks,
Yeachan
